import { app, BrowserWindow, ipcMain } from 'electron';
require('@electron/remote/main').initialize()
import { v4 } from 'uuid';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const fs = require("fs/promises");

// ipcMain.handle("getTopics", async (event) => {
//   fs.readFile('topics.json', function(err: any, data: any) { 
//             if (err) throw err; 
//             return "hi"
//         }); 
// });



const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 1400,
    width: 800,
    minHeight:350,
    minWidth:200,
    backgroundColor: 'whitesmoke',
    titleBarStyle: 'hidden',
    titleBarOverlay: {
      color: '#d1d1d1',
      symbolColor: '#e76b31',
      height:40,
      
    },
    
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: true,
      contextIsolation: true,
      sandbox:false,
    },
    
  });
  require("@electron/remote/main").enable(mainWindow.webContents)
  mainWindow.setBackgroundColor('#d1d1d1')
  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  mainWindow.maximize();

  // Open the DevTools.
  mainWindow.webContents.openDevTools()
};


// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.


ipcMain.handle("get-topics", async (_event, filePath: string) => {
  //console.log("main got:", filePath);
  //Main needs to access FS
  try {
    const data = await fs.readFile(filePath, 'utf8');
    return { success: true, data };
    
  } catch (error: any) {
    return { success: false, error: error.message };
  }

});

ipcMain.handle("add-topic", async (_event, topicName: string) => {

  const data = {}
  const testData = await fs.readFile("src/topics.json", 'utf8')

  try {


    
    const JSONData = JSON.parse(testData)
    JSONData[v4()] = {
        "topicTitle": topicName,
        "topicStatus": false
    }

    const stringData = JSON.stringify(JSONData, null, "\t")
    console.log(JSONData)
    await fs.writeFile("src/topics.json", stringData)

    
    return { success: true}

  } catch(error:any) {
    return { success: false}
  }


  //console.log("main got:", filePath);
  //Main needs to access FS
  // try {
  //   const data = await fs.readFile(filePath, 'utf8');
  //   return { success: true, data };
    
  // } catch (error: any) {
  //   return { success: false, error: error.message };
  // }
  


});


app.on('ready', createWindow);




// Source - https://stackoverflow.com/a/43722580
// Posted by Rohith K P, modified by community. See post 'Timeline' for change history
// Retrieved 2026-05-23, License - CC BY-SA 3.0






// app.whenReady(()=> {

// })


// app.on('ready', () => {


//     fs.readFile("src/topics.json", 'utf-8', (err: any, data: any) => {
//         if(err){
//             console.log("An error ocurred reading the file :" + err.message);
//             return;
//         }

//         // Change how to handle the file content
//         const jsonObject = JSON.parse(data);
//         console.log(jsonObject);
//     });
// });


// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.



