import { app, BrowserWindow, ipcMain } from 'electron';
require('@electron/remote/main').initialize()
import { v4 } from 'uuid';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}
const fs = require("fs/promises");

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 1400,
    width: 800,
    minHeight:350,
    minWidth:200,
    backgroundColor: 'whitesmoke',
    titleBarStyle: 'hidden',
    titleBarOverlay: {
      color: '#d1d1d1',
      symbolColor: '#e76b31',
      height:40,
      
    },
    
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: true,
      contextIsolation: true,
      sandbox:false,
    },
    
  });
  require("@electron/remote/main").enable(mainWindow.webContents)
  mainWindow.setBackgroundColor('#d1d1d1')
  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  mainWindow.maximize();


  //Open Dev Tools
  mainWindow.webContents.openDevTools()
};

ipcMain.handle("get-decks", async (_event, filePath: string) => {
  try {
    const data = await fs.readFile(filePath, 'utf8');
    return { success: true, data };
    
  } catch (error: any) {
    return { success: false, error: error.message };
  }

});


ipcMain.handle("delete-deck", async (_event, key:number) => {

  try {
    const testData = await fs.readFile("src/topics.json", 'utf8')
    const JSONData = JSON.parse(testData)

    let newData: any = {}

    Object.entries(JSONData).map((i: any, k: number) => {
      if(k != key) {
        newData[i[0]] = i[1]
      }
    })

    const stringData = JSON.stringify(newData, null, "\t")
    await fs.writeFile("src/topics.json", stringData)

    return {success: true}

  } catch(err: any) {
    return {success:false}
  }
})


ipcMain.handle("get-cards-from-deck", async (_event, key: number) => {
  try {

    const testData = await fs.readFile("src/topics.json", "utf8")
    const JSONData = JSON.parse(testData)

    let newData: any = {}
    Object.entries(JSONData).map((i: any, k: number) => {
      if(k == key) {
        newData[i[0]] = i[1]
      }
    })

    return {success:true, data: newData}
  } catch(error:any) {
    return {success:false, data: null}
  }
})

ipcMain.handle("rename-deck", async (_event, key:number, rename:string) => {
  try {
    const testData = await fs.readFile("src/topics.json", "utf8")
  
    const JSONDataTemp = JSON.parse(testData)
  
    let newData: any = {}
    Object.entries(JSONDataTemp).map((i: any, k:number) => {
      if(k == key) {
        let testVal = i[1]
        testVal.topicTitle = rename
        newData[i[0]] = testVal
      }
      else {
        newData[i[0]] = i[1]
      }
    })
    const stringData = JSON.stringify(newData, null, "\t")
    await fs.writeFile("src/topics.json", stringData)
    return {success: true}

  } catch(error: any) {
    return {success:false}
  }


})


ipcMain.handle("add-card", async (_event, deckId: string, front:string, back: string) => {
  try {
    const testData = await fs.readFile("src/topics.json", 'utf8')
  
    const JSONDataTemp = JSON.parse(testData)

    if(JSONDataTemp[deckId].deckStatus) {
      console.log("This deck has cards")
      JSONDataTemp[deckId].cards = [...JSONDataTemp[deckId].cards, [front, back]]
    }
    else {
      console.log("this deck has no cards")
      JSONDataTemp[deckId].deckStatus = true
      JSONDataTemp[deckId].cards = [[front, back]]
      
    }

    const stringData = JSON.stringify(JSONDataTemp, null, "\t")
    await fs.writeFile("src/topics.json", stringData)

    return {success:true}
  }
  catch(err: any) {
    return {success:false}
  }

})


ipcMain.handle("add-deck", async (_event, deckName: string) => {



  const testData = await fs.readFile("src/topics.json", 'utf8')
  
  const JSONDataTemp = JSON.parse(testData)
  let len = 0
  for(var a in JSONDataTemp){
    if(a != "status") len += 1
  }

  if(len < 15) {
    try {
      const JSONData = JSON.parse(testData)
      JSONData[v4()] = {
          "deckTitle": deckName,
          "deckStatus": false
      }
  
      const stringData = JSON.stringify(JSONData, null, "\t")
      await fs.writeFile("src/topics.json", stringData)
  
      
      return { success: true, maxTopicError: false}
  
    } catch(error:any) {
      return { success: false, maxTopicError: false}
    }

  }
  else {
    return { success: false, maxTopicError: true}
  }

  
});




app.on('ready', createWindow);




// Source - https://stackoverflow.com/a/43722580
// Posted by Rohith K P, modified by community. See post 'Timeline' for change history
// Retrieved 2026-05-23, License - CC BY-SA 3.0






// app.whenReady(()=> {

// })


// app.on('ready', () => {


//     fs.readFile("src/topics.json", 'utf-8', (err: any, data: any) => {
//         if(err){
//             console.log("An error ocurred reading the file :" + err.message);
//             return;
//         }

//         // Change how to handle the file content
//         const jsonObject = JSON.parse(data);
//         console.log(jsonObject);
//     });
// });


// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.



